nodeLinker: "node-modules"

yarnPath: "D:\\workspace\\temp\\yarn-berry-bug-patch\\.yarn\\releases\\yarn-berry.js"

packageExtensions: 
  webpack@*:
    dependencies: 
      watchpack: "patch:watchpack@1.6.1#./.fix-symlinks.patch"